### ISSUE TITLE
不断提示 更新 0.9.1

### ISSUE THREAD

**Issue by jacktator** [leancloud/avoscloud-code-command#101]
即使sudo npm install -g avoscloud-code后，仍然不断提示。
![screen shot 2015-11-04 at 1 12 11 pm](https://cloud.githubusercontent.com/assets/5646140/10927754/8bfe664a-82f6-11e5-904d-04cdea284c42.png)

**Comment by sdjcw** [comment]
你好，请问你现在执行命令： `avoscloud -V` 是什么结果？

**Comment by jacktator** [comment]
![screen shot 2015-11-05 at 5 37 06 am](https://cloud.githubusercontent.com/assets/5646140/10947988/487abdb8-837f-11e5-9ee7-52e64409394b.png)

**Comment by jacktator** [comment]
可是确实可以在 全局 上 `avoscloud` 打开localserver的
![screen shot 2015-11-05 at 5 40 12 am](https://cloud.githubusercontent.com/assets/5646140/10948058/b8fadfa0-837f-11e5-8fa6-9740a887247d.png)

**Comment by jacktator** [comment]
发现版本了，0.8.0
![screen shot 2015-11-05 at 5 43 58 am](https://cloud.githubusercontent.com/assets/5646140/10948173/5a0b7b98-8380-11e5-90ad-d64756526c05.png)
可是奇怪的是，我就算 sudo npm install -g avoscloud-code 了无数次，每次npm都说装好了，这个似乎都没有更新。。。
![screen shot 2015-11-05 at 5 46 49 am](https://cloud.githubusercontent.com/assets/5646140/10948222/abbbedc4-8380-11e5-92ab-5fa367e17f37.png)

**Comment by jacktator** [comment]
貌似找到问题了，sudo npm install -g一直安装在 `/usr/local/lib/node_modules/` 中，
而 Terminal run的时候，必须装在 `/opt/local/lib/node_modules` 中。
估计是我 本机 的 NPM install 配置问题吧。
