### ISSUE TITLE
部署可以配置 ignore 的文件

### ISSUE THREAD

**Issue by wangxiao** [leancloud/avoscloud-code-command#109]
希望是：被 ignore 的文件，本地 deploy 的时候，不会发布到 LeanEngine 中。

**Comment by callmewhy** [comment]
+1，另外希望 ignore 的文件不会触发 avoscloud 命令里 nodemon 的自动更新

**Comment by soargon** [comment]
+1

**Comment by aisk** [comment]
close by: https://github.com/leancloud/avoscloud-code-command/pull/121
