### ISSUE TITLE
支持配置不 watch 某些文件的变化

### ISSUE THREAD

**Issue by wangxiao** [leancloud/avoscloud-code-command#110]

**Comment by watert** [comment]
同样觉得很重要，虽然是基于nodemon，但似乎在`runtime.js`里看到watch的只是/cloud目录，实际却是全部都watch了，包括public里的内容……

而我尝试添加global的或local的`nodemon.json`却似乎都不生效，希望能予以支持

**Comment by jysperm** [comment]
抱歉该项目不会再维护了，命令行工具已用 Golang 重写，仓库在 https://github.com/leancloud/lean-cli 使用文档在 https://leancloud.cn/docs/leanengine_cli.html

新版命令工具中是允许用户自定义代码重启的行为的，你可以调整 nodemon 的配置文件来控制这个行为。
