### ISSUE TITLE
Redis Cli 支持在参数中提供命令、在标准输出返回结果

### ISSUE THREAD

**Issue by jysperm** [leancloud/avoscloud-code-command#116]
有用户希望用 shell 脚本对 Redis 完成一些自动化操作，如果支持在参数中提供命令、在标准输出返回结果，将会非常方便，类似 `redis-cli` 的行为：

```
avoscloud redis cache1 keys '*' | xargs avoscloud redis cache1 del
```

**Comment by aisk** [comment]
我还是想通过开启一个临时 ssh 隧道的方式给用户提供命令行工具，以后有其他我们想要集成的服务，实现起来相对也容易。
