### ISSUE TITLE
执行 avoscloud add 时判断 .avoscloud/ 是否已被添加到 .gitignore 文件

### ISSUE THREAD

**Issue by guo-yu** [leancloud/avoscloud-code-command#117]
现在执行 avoscloud add 不同项目时，会将 .avoscloud/ 一行重复添加到这个项目的 .gitignore 文件，造成一个不稳定修改。建议先判断 .gitignore 文件中是否已经包涵 .avoscloud/

**Comment by callmewhy** [comment]
+1

**Comment by sdjcw** [comment]
该特性已经在 v0.10 支持。
