### ISSUE TITLE
avoscloud deploy 时常抛出 ECONNREFUSED 错误

### ISSUE THREAD

**Issue by guo-yu** [leancloud/avoscloud-code-command#118]
详细日志如下：
```
[INFO] 开始上传项目文件……
2016-01-19 12:55:57 [INFO] 命令行部署应用……
2016-01-19 12:55:57 [INFO] 获取部署包
2016-01-19 12:55:57 [INFO] 解压缩部署包
2016-01-19 12:55:57 [INFO] 运行环境: Node.js
2016-01-19 12:55:57 [INFO] 安装新的依赖
2016-01-19 12:57:01 [INFO] 备份最新的依赖包
2016-01-19 12:59:32 [INFO] 项目代码分发
2016-01-19 13:00:35 [INFO] 创建新的容器
2016-01-19 13:00:36 [INFO] 应用启动检测
2016-01-19 13:00:53 [ERROR] 命令行部署应用失败: Error: updateContainers err: Error: 应用启动检测失败: Error: connect ECONNREFUSED
抱歉，部署失败 失败：命令行部署应用失败: Error: updateContainers err: Error: 应用启动检测失败: Error: connect ECONNREFUSED
查看使用帮助：avoscloud -h，或查看相关文档：https://leancloud.cn/docs/cloud_code_commandline.html
```

**Comment by guo-yu** [comment]
重新部署时显示部署成功，但访问显示「No Application Configured」
详细日志如下：
```
[INFO] 开始上传项目文件……
2016-01-19 13:03:46 [INFO] 命令行部署应用……
2016-01-19 13:03:46 [INFO] 获取部署包
2016-01-19 13:03:47 [INFO] 解压缩部署包
2016-01-19 13:03:47 [INFO] 运行环境: Node.js
2016-01-19 13:03:47 [INFO] 从缓存恢复依赖包
2016-01-19 13:06:08 [INFO] 安装新的依赖
2016-01-19 13:06:42 [INFO] 备份最新的依赖包
[INFO] 部署成功
项目状态：
------------------------------------------------------------------------
测试环境版本     : 'null'
测试环境提交日志 : 'null'
生产环境版本     : 'null'
生产环境提交日志 : 'null'
------------------------------------------------------------------------
```

**Comment by aisk** [comment]
下面这词部署应该也是失败了的，如果成功的话最后的结果应该不是 null。这个应该是我们的 bug，近期内会进行改进的，暂时麻烦先重拾一下。

**Comment by guo-yu** [comment]
好的，谢谢

**Comment by guo-yu** [comment]
@aisk 
我看了平台上显示的详细日志，实际上是 babel 的 require hook 没有执行成功，导致：
```
import path from 'path';
ERROR 2016-01-19 15:52:58 SyntaxError: Unexpected reserved word
```
关于 bebel 的模块和 require hook，我在本地以 lean engine 线上相同的 Node 版本（也就是 node v0.12.7）测试过，是没问题的。在 deps 中也添加了 babel-core 和 babel-register，包括 babel-preset-es2015 的相关依赖。想问一下如何更近一步的 debug 是什么原因导致了 require hook 失效？可以在 cli 或者平台上查询到当前沙箱的 npm ls 情况吗？

**Comment by aisk** [comment]
@guo-yu 这个功能暂时还不支持。能否发一下 app id 给我看下原因吗？如果涉及隐私可以发到我的邮箱： lan#leancloud.rocks

**Comment by guo-yu** [comment]
@aisk 
appId 是 `	bxJEaGVlxFK732ASpkr3M1V0-gzGzoHsz` 
因为 LeanEngine Full Stack 那个 repo 也是用同一种方式的 require hook 支持部分 ES6 的，所以我以为任意的 babel 版本应该都可以获得支持~

**Comment by aisk** [comment]
我怀疑可能是没在  package.json['scripts']['start'] 里写 "node --harmony xxx.js"

**Comment by guo-yu** [comment]
@aisk 
这个我在本地测试过同样版本的 Node 程序，使用 require hook 时是不需要标注相关 flag 的，看错误日志，我猜想是因为 preset 没有被加载，或指定的 .babelrc 文件没有上传，能麻烦帮我看一下这个项目真实的服务器文件吗？

这个模块：/node_modules/babel-preset-es2015
这个文件：/.babelrc

**Comment by aisk** [comment]
.babelrc 没有被上传

**Comment by guo-yu** [comment]
看来应该是这个问题了，执行 avoscloud 打包文件时会忽略 dot files 吗？

**Comment by aisk** [comment]
应该是没有这个特殊逻辑的。

**Comment by guo-yu** [comment]
@aisk 
我看到 Full Stack 那个项目中 dot file 是在文件夹中被上传的，我尝试一下不放在项目根目录，但仍然报同样的错误

**Comment by aisk** [comment]
应该是放在执行 avoscloud deploy 的目录下，还是不行吗？

**Comment by aisk** [comment]
麻烦顺便检查一下这次的错误原因依然是这个导致的。

**Comment by guo-yu** [comment]
仍然是这个问题，我在继续寻找解决办法

**Comment by guo-yu** [comment]
@aisk 
将所有 babel 相关依赖移入 dependencies 后 deploy 成功~
