### ISSUE TITLE
命令行工具支持部署 us 节点的应用

### ISSUE THREAD

**Issue by sdjcw** [leancloud/avoscloud-code-command#126]
增加 LC_SERVER 环境变量，命令行工具请求 REST API 时使用该变量。用户可以自定义该变量的值，指定 us 节点的服务地址，使命令行工具可以部署 us 节点应用。

**Comment by jysperm** [comment]
LeanEngine 上是叫 `LC_API_SERVER`

**Comment by juvenn** [comment]
`LC_API_REGION` 怎么样？

**Comment by jysperm** [comment]
两者都要加，LC_API_REGION 的格式类似 `US`，LC_SERVER 的格式类似 `http://us-api.leancloud.cn`

**Comment by juvenn** [comment]
我跟 @feisuzhu 建议过中国节点加 https://cn-api.leancloud.cn 。这样有了 LC_API_REGION 就可以构造 server url 了。

**Comment by jysperm** [comment]
LC_SERVER 在云引擎上会被覆盖成内网地址，所以还是有必要维护一个单独的 LC_SERVER 变量。

**Comment by juvenn** [comment]
明白了。

**Comment by jysperm** [comment]
已在 https://github.com/leancloud/avoscloud-code-command/pull/144 实现
