### ISSUE TITLE
打包时包括点开头的文件

### ISSUE THREAD

**Issue by jysperm** [leancloud/avoscloud-code-command#127]
https://forum.leancloud.cn/t/babel/6861
但不包括 `.git` 和 `.avoscloud`

**Comment by wangxiao** [comment]
这个问题比较严重，如果用户用 babel 的话，会很迷糊，怎么也不好使。如果暂时不修复的话，建议可以先在文档中给出提示。「lean deploy 会忽略以点开头的文件。」

**Comment by jysperm** [comment]
点开头的文件大部分还是不需要上传的，这也是 Unix 下的一般约定，所以决定只针对 .babelrc 这类文件添加特例，同时用户可以在 .leanengineignore 中控制这个行为
