### ISSUE TITLE
命令行提示信息不够

### ISSUE THREAD

**Issue by jwfing** [leancloud/avoscloud-code-command#129]
https://forum.leancloud.cn/t/topic/7080

**Comment by callmewhy** [comment]
一模一样的问题，0.11.0版，郁闷

**Comment by sdjcw** [comment]
用户反馈之后出现问题的错误对象是： 

`{"code":-1,"error":{"code":"ECONNRESET","name":"RequestError"},"action":"部署应用"}`

**Comment by jysperm** [comment]
1.0.0 中已将服务器返回的错误信息原样显示给客户端
