### ISSUE TITLE
远程调试支持 remote debug support

### ISSUE THREAD

**Issue by Diluka** [leancloud/avoscloud-code-command#131]
现在用`-d`参数启动本地项目，会自动附加一个命令行调试器；为了调试更加方便，能不能不自动附加命令行调试器，让开发者可以自行连接外部调试器

**Comment by Diluka** [comment]
已解决
```
"scripts": {
    "start":"node --debug-brk=5858 server.js"
  }
```

添加此参数即可开启调试端口，之后用其他调试工具attach到这个端口便可调试。p.s.5858是nodejs默认调试端口，理论上可以填写任意未使用的端口

**Comment by aisk** [comment]
@Diluka 因为命令行工具后续打算支持多语言(Python / node / PHP)，所以恐怕不能集成这么多 node 相关的功能。

**Comment by Diluka** [comment]
@aisk 直接写在scripts.start里面部署到云端会出错的，每次都得去掉
