### ISSUE TITLE
应用名为中文时，lean new 创建项目失败

### ISSUE THREAD

**Issue by myleslee** [leancloud/avoscloud-code-command#133]
用户反馈：

<img width="908" alt="screen shot 2016-04-07 at 11 26 17" src="https://cloud.githubusercontent.com/assets/108758/14339975/49d4258c-fcb5-11e5-8479-768fb7e1d61e.png">

**Comment by myleslee** [comment]
与 #112 重复了

**Comment by aisk** [comment]
duplicated with: #133
