### ISSUE TITLE
云函数调试请求地址能不能不定死成 localhost

### ISSUE THREAD

**Issue by brentybh** [leancloud/avoscloud-code-command#140]
导致我这 localhost 死都解析不了，hosts 不生效，不能调试。
还有在 Web IDE 等环境中由于定死了请求端口，导致 Web IDE 转发出来的 80/443 端口的调试网址无法使用。
希望可以自定义调试请求地址。

**Comment by jysperm** [comment]
https://leanticket.cn/t/leancloud/2430

**Comment by jysperm** [comment]
抱歉该项目不会再维护了，命令行工具已用 Golang 重写，仓库在 https://github.com/leancloud/lean-cli 使用文档在 https://leancloud.cn/docs/leanengine_cli.html

新版命令行工具中已解决这个问题
