### ISSUE TITLE
无法运行原 cloud-code2 应用

### ISSUE THREAD

**Issue by jysperm** [leancloud/avoscloud-code-command#156]
![image](https://cloud.githubusercontent.com/assets/1191561/16333640/ee0515a6-3a2e-11e6-93f2-998fb1caf96a.png)

为了支持腾讯云把依赖的 avoscloud-sdk 升级到了 1.0.0-rc9.2，但这个版本有很多不兼容的 API 改动，看来需要单独依赖一个比较旧版本的 avoscloud-sdk 来支持原 cloud-code2 项目。

**Comment by aleonchen** [comment]
hi，升级了最新的 avoscloud-code@1.3.1，在使用lean up,也出现同样的问题。请问下要怎么解决？

**Comment by jysperm** [comment]
暂时还没有修复对 cloud-code2 的支持，如果你没有用到新版本的功能可以考虑回滚到 1.1 版本 `npm install -g avoscloud-code@1.1.0`
