### ISSUE TITLE
lean up 提供一种不监视文件变化的启动方式

### ISSUE THREAD

**Issue by jysperm** [leancloud/avoscloud-code-command#163]
有的用户希望自行接管监视文件变化并重启程序这个行为，因为我们目前并不能配置监视文件时忽略的文件列表，所以应该提供一种不监视文件变化的启动方式

**Comment by jysperm** [comment]
打算添加一个 `lean up --no-watch` 命令来不 watch 任何文件，同时如果当前目录下有 nodemon.json 的话，则使用里面的配置（这个行为和 nodemon 一致）。

**Comment by Axure** [comment]
赞同。刚刚想提出这个 issue。似乎 cloud code 模式 watch 的是 cloud，而 nodejs 模式会 watch 所有。

现在我采用的权宜之策是手动将配置拷贝到需要 watch 的文件夹，这样很不优雅，也不够灵活。

**Comment by jysperm** [comment]
抱歉该项目不会再维护了，命令行工具已用 Golang 重写，仓库在 https://github.com/leancloud/lean-cli 使用文档在 https://leancloud.cn/docs/leanengine_cli.html

新版命令工具中是允许用户自定义代码重启的行为的，你可以调整 nodemon 的配置文件来控制这个行为。
