### ISSUE TITLE
粘贴 Master Key 成功时给予明确显示

### ISSUE THREAD

**Issue by wangxiao** [leancloud/avoscloud-code-command#165]
![image](https://cloud.githubusercontent.com/assets/558368/16833948/1e36608a-49e4-11e6-837d-6ac6f78dfd04.png)

如图粘贴 app id 时能够给予明确显示，但是粘贴 Master key 时却不是，所以让人觉得没有粘贴成功，不知道该不该敲回车。建议干脆 master key 也显示出来吧，其实显示出来没有人能背下来吧。

另外，最好配置流程是前置的。就是说流程是 1、输入 app id；2、输入 master key；3、选择模板；现在选择模板在前面，顺序有点奇怪。

**Comment by leeyeh** [comment]
一般输密码都是没有任何反馈的。

**Comment by wangxiao** [comment]
对的，但是这个和密码不完全相同，一般密码完全是输入的，但这个 master key 基本都是复制粘贴。主要是上面让输入 app id 是显示的，下面又输入 master key （也需要复制粘贴）却是不显示，不如都显示体验好。
