### ISSUE TITLE
显示中总有 3001 端口容易混淆调试端口

### ISSUE THREAD

**Issue by wangxiao** [leancloud/avoscloud-code-command#166]
![image](https://cloud.githubusercontent.com/assets/558368/17077470/e8812624-5103-11e6-98aa-e359ed6d4b18.png)

这里写的是云函数，但是因为没有说清楚已经开启了 3000 端口，容易让人误会，所以建议修正下提示。

「提示：LeanEngine 服务已经运行在 3000 端口，测试 Cloud 函数 http://localhost:3001 」

**Comment by jysperm** [comment]
和 https://github.com/leancloud/cloud-code/issues/323 重复
