### ISSUE TITLE
lean new 命令如果有可能覆盖文件需二次确认

### ISSUE THREAD

**Issue by leeyeh** [leancloud/avoscloud-code-command#169]
https://leanticket.cn/t/leancloud/2485

**Comment by tooyond** [comment]
很严重的问题 我昨天晚上因为执行new命令的时候 输错了appid 导致直接覆盖了我已有的项目代码 希望尽早解决

**Comment by jysperm** [comment]
抱歉该项目不会再维护了，命令行工具已用 Golang 重写，仓库在 https://github.com/leancloud/lean-cli 使用文档在 https://leancloud.cn/docs/leanengine_cli.html

新版的命令行工具中会在已有文件的情况下返回一个错误。
