### ISSUE TITLE
忽略一些没必要的文件变更提示

### ISSUE THREAD

**Issue by wangxiao** [leancloud/avoscloud-code-command#170]
![image](https://cloud.githubusercontent.com/assets/558368/17617066/74f143c2-60aa-11e6-88c2-96cad32f3806.png)
文件变更提示很容易出现一堆，某些文件变革可以忽略掉，比如升级 node_modules 之后。

**Comment by jysperm** [comment]
和 https://github.com/leancloud/avoscloud-code-command/issues/163 重复

**Comment by wangxiao** [comment]
与 #163 还不太一样，我这个主要是说展示上面的优化，底层可以仍然 watch，展示上不要把一下子全列出来。

**Comment by jysperm** [comment]
抱歉该项目不会再维护了，命令行工具已用 Golang 重写，仓库在 https://github.com/leancloud/lean-cli 使用文档在 https://leancloud.cn/docs/leanengine_cli.html

新版命令工具中是允许用户自定义代码重启的行为的，你可以调整 nodemon 的配置文件来控制这个行为。
