### ISSUE TITLE
更新GO语言的lean-cli之后node的命令行工具是否持续更新？

### ISSUE THREAD

**Issue by qinyuhang** [leancloud/avoscloud-code-command#171]
RT，在LeanCloud微信公众号看到了新的GO语言的命令行工具，是否以后停止更新node的命令行工具呢？

**Comment by aisk** [comment]
您好，go 版本的命令行工具开发的一个主要目的就是取代现有 node 版本的命令行工具的，在达到这个目标之后应该会停止 node 版本的开发。不过在此之前 node 版本的开发与维护应该不会停止。

因此如果您有需求或者想要贡献代码的话，欢迎提到 go 版本的 repo 里。

**Comment by qinyuhang** [comment]
了解了。以后就尽量提到 Go 版本的 repo了

Long Ang <notifications@github.com>于2016年8月30日 周二19:02写道：
