### ISSUE TITLE
部署云代码时偶尔会401 Unauthorized

### ISSUE THREAD

**Issue by fxp** [leancloud/avoscloud-code-command#23]
部署的时候偶尔会出现error 401 Unauthorized，重试几遍就会成功。其中一次的log如下

    MacBook:xxx_CloudCode fengxiaoping$ avoscloud deploy
    [INFO]: Cloud Code Project Home Directory: /xxx/xxx_CloudCode/
    [INFO]: Current App: origin 5uzb76lzdkmrgbll3ib3gizg1o88lyw3jhsqvbc8e7iqnilx
    Compress cloud code files...
    Wrote compressed file /var/folders/ft/jfytvs8d0yn1lfhsw9n4448w0000gn/T/1417684988110.tar.gz ...
    Begin to upload cloud code files...
    Upload cloud code files successfully. Begin to deploy...
    Sorry, try to deploy cloud code failed with '{"code":401,"error":"Unauthorized."}'

**Comment by killme2008** [comment]
貌似现在没有人再反馈了，不知道各位有没有升级到最新版本试试？

**Comment by dengbo22** [comment]
我又遇到了一次,Android平台,调试系统是Ubuntu14.04
