### ISSUE TITLE
能否增加非项目部署相关的功能，比如说将 api 报表导出 csv

### ISSUE THREAD

**Issue by sdjcw** [leancloud/avoscloud-code-command#31]
@wanggc 希望能在命令行工具直接导出一些 api 报表的 csv 供用户使用。
使用这些功能的不是开发，可能是运营同学，所以执行该命令时时不会有一个「代码目录」的。

能否增加一个 avoscloud init 的参数，然后只填写 appId 和 masterKey 信息，然后当前目录就作为一个「工作目录」，可以执行一些命令，比如 CQL，或者导出数据什么的。

不过需要考虑一个问题：权限如何划分，因为统计数据的获取是需要 masterKey 的，但是有可能会出现防止运营人员 deploy 的动作。

我们是否做个使用「账号密码」方式初始化命令行呢？
命令行是否能作为一个功能更丰富的客户端呢？

**Comment by killme2008** [comment]
暂时不考虑了，这跟命令行工具不“搭嘎”
