### ISSUE TITLE
添加package.json之后会报错找不到对应的modules

### ISSUE THREAD

**Issue by zEmily** [leancloud/avoscloud-code-command#55]
> [云代码升级到2.0](https://leancloud.cn/docs/cloud_code_guide.html#升级到_2_0) 这里提及可以使用package.json 引入自己额外添加的第三方类库。

### 我想引入某个第三方库
但是我不太明白这个后续要如何操作？
虽然 自己在本地`npm install`之后运行`avoscloud`能够顺利跑起来，但是部署到云环境里的话，是怎么办呢？云环境里会自动运行`npm install`指令么？我测试下来好像没有这样，所以导致很多想引入的modules都是没有的，就报错了。

请教 是需要做什么能让云代码上也install 第三方库呢？谢谢了~

**Comment by aisk** [comment]
您好，云代码环境会自动执行 npm install ，请麻烦确认一下您的所有依赖都已经写在 package.json 中了。

**Comment by zEmily** [comment]
就是说，即使是在本地操作，也不需要手动执行`npm install`是么？

**Comment by aisk** [comment]
本地是需要的。

**Comment by zEmily** [comment]
谢谢哦~~疑问消除
