### ISSUE TITLE
如果我只是想使用gulp，就一定要使用javascript-sdk 么？

### ISSUE THREAD

**Issue by zEmily** [leancloud/avoscloud-code-command#57]
你好，我希望使用gulp来构建我的前端，本地是可以直接命令行输入`gulp`就执行各种操作的。但是到了云端该怎么办呢？？？
我参考了一下[javascript-sdk](https://github.com/leancloud/javascript-sdk) 里的说法，但是我只是希望能够简单地使用gulp，就一定要安装javascript-sdk么？还是有其他途径呢？
谢谢哦～～～～

**Comment by aisk** [comment]
没有明白您要用 gulp 实现什么事情，如果您需要单独使用 gulp，直接安装 gulp，并且参考官方文档写 gulpfile 就可以了。如果您想要在 LeanCloud 的云代码项目上使用 gulp 来构建前端，可以在本地将项目构建好，一并传到云代码上。

**Comment by zEmily** [comment]
好的，我明白了。我现在是使用本地构建好上传到云代码的。谢谢了。
