### ISSUE TITLE
增加 debug 支持

### ISSUE THREAD

**Issue by aisk** [leancloud/avoscloud-code-command#59]
现在代码是在 avoscloud 里面 fork 进程之后再运行的，debug 工具都无法观测到子进程的断点信息。

**Comment by aleonchen** [comment]
关注，这样碰到问题可以自己先调试一下 :)

**Comment by killme2008** [comment]
增加了 `-d` 或者 `--debug` 选项，马上发布。

**Comment by killme2008** [comment]
发布 v0.7.0
