### ISSUE TITLE
使用 AVOScloud new 等方法都是好好的，但是 无法使用 avoscloud 开启本地部署

### ISSUE THREAD

**Issue by gybin02** [leancloud/avoscloud-code-command#61]
想在本地调试 云主机 工程，根据 Guide 一步步走下去，创建工程， 但是执行avoscloud 本地启动这步出错了。无法执行。。

D:\gitosc\gitCloud\cloudcode-test>avoscloud status
[INFO]: Cloud Code Project Home Directory: D:\gitosc\gitCloud\cloudcode-test\
[INFO]: Current App: origin wjm04batbnzn0rigyo6zzwcz5rzntlyvgv3l6y7bsy2bncy9
请输入应用的 Master Key (可从开发者平台的应用设置里找到):
Cloud code status is:
------------------------------------------------------------------------
Development version    : '8f481a6193a0c8152a5e21baf9ab1827d08cdf18'
Development commit log : '1. change Key And Id.'
Production version     : '8f481a6193a0c8152a5e21baf9ab1827d08cdf18'
Production commit log  : '1. change Key And Id.'
------------------------------------------------------------------------

D:\gitosc\gitCloud\cloudcode-test>avoscloud
提示：您可以敲入 rs 命令并回车来重启本进程
module.js:338
    throw err;
          ^
Error: Cannot find module 'D:\gitosc\gitCloud\cloudcode-test\"C:\Program'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by aisk** [comment]
`'D:\gitosc\gitCloud\cloudcode-test\"C:\Program'` 这个包是什么东西？

**Comment by killme2008** [comment]
建议在 c 盘试试。

**Comment by killme2008** [comment]
nodejs 安装到  c 盘即可，这个先关闭了，可以关注
https://github.com/leancloud/avoscloud-code-command/issues/66
