### ISSUE TITLE
因为 _File 表有 ACl 限制，导致命令行部署上传包时失败

### ISSUE THREAD

**Issue by sdjcw** [leancloud/avoscloud-code-command#64]
错误信息：`Upload cloud code files failed with '"{\"code\":1,\"error\":\"Forbidden to create by class permissions.\"}"'`

应该时上传包后，向 _File 表添加记录时没有权限。是否使用 masterKey 来写 File 表的记录？

相关ticket：https://ticket.avosapps.com/tickets/553f54e5e4b05b80583c9240/threads

**Comment by killme2008** [comment]
发布 0.7.1
