### ISSUE TITLE
获取版本信息支持小写 v 参数

### ISSUE THREAD

**Issue by wangxiao** [leancloud/avoscloud-code-command#85]
貌似一般都是小写的 v，现在是大写 V 很奇怪，或者都支持下。
![image](https://cloud.githubusercontent.com/assets/558368/9189252/a663205a-4018-11e5-8b7b-4517637a144b.png)

**Comment by aisk** [comment]
大写 V 很常见，小写很多情况下是 --verbose 的缩写。

**Comment by killme2008** [comment]
大写 V 应该是符合国际惯例的。

**Comment by wangxiao** [comment]
可是为啥随便试了几个常用的工具都不是大写 V 。。。

![image](https://cloud.githubusercontent.com/assets/558368/9731167/ef6ad5e0-564d-11e5-8757-2278f13ceacd.png)

**Comment by aisk** [comment]
你试的全部都是 node 社区的……

**Comment by wangxiao** [comment]
好吧，小问题，听专业的。
