### ISSUE TITLE
这个地方是故意这样写的吗？

### ISSUE THREAD

**Issue by GongT** [leancloud/avoscloud-code-command#86]
https://github.com/leancloud/avoscloud-code-command/blob/master/lib/runtime.js#L80

**Comment by aisk** [comment]
目前是这样的，因为命令行工具之保存了 master key，之前老版本的运行时也只支持 master key 运行。我们会在后续版本改成支持 app key 的。

**Comment by jysperm** [comment]
已解决： https://github.com/leancloud/avoscloud-code-command/pull/96
