### ISSUE TITLE
是否可以用云代码命令行工具下载云代码

### ISSUE THREAD

**Issue by sleepgod** [leancloud/avoscloud-code-command#87]
我用云代码命令行工具上传了云代码，现在本地没有代码了，想从leancloud服务端下载一份云代码，现在没法操作.

**Comment by aisk** [comment]
暂时不支持。可以把您的应用 app / master key 邮件发给我(lan at leancloud.rocks)，我帮您找回。

**Comment by sleepgod** [comment]
我购买了技术支持，提交了工单。已经解决了 谢谢你！
