### ISSUE TITLE
多次提示 AVOSCloud SDK is already initialized, please don't reinitialize it.

### ISSUE THREAD

**Issue by lzwjava** [leancloud/avoscloud-code-command#89]
![image](https://cloud.githubusercontent.com/assets/5022872/9718111/71a081e8-55ab-11e5-96a1-90a60b243372.png)

**Comment by sdjcw** [comment]
v0.7.8 已经 fix 该问题，确认下你当前使用的版本。

**Comment by lzwjava** [comment]
嗯，升级后没问题了。
