### ISSUE TITLE
输入 Master Key 时校验正确性

### ISSUE THREAD

**Issue by wangxiao** [leancloud/avoscloud-code-command#91]
没有校验 Master Key，输入错了，后续部署会失败，很难发现原因。

**Comment by jysperm** [comment]
在 https://github.com/leancloud/avoscloud-code-command/pull/96 输入 masterKey 之后会去查询 appKey, 因此如果 masterKey 有误的话会提示，并不会保存到文件，可以说顺便解决了这个问题。

**Comment by wangxiao** [comment]
好的，有错误提示就好。
