### ISSUE TITLE
部署时输出的信息优化

### ISSUE THREAD

**Issue by wangxiao** [leancloud/avoscloud-code-command#93]
![image](https://cloud.githubusercontent.com/assets/558368/10095832/47db3f0e-639f-11e5-866f-d3bb3cd13b74.png)

* 部署成功信息太长，最好能够和其他的一致。将 commit 和 log 分成两个写，更清晰友好；
* 没有发布过生产环境，生产环境那个地方会显示为 null，这种情况这两行最好就不显示了；

**Comment by GongT** [comment]
不能不显示啊，否则除了问题不好找

**Comment by wangxiao** [comment]
不是说每条都不显示，null 这种情况可以不显示，应该是一个 Bug。
> 不能不显示啊，否则除了问题不好找

**Comment by jysperm** [comment]
在新版云引擎和命令行 0.11 之后已解决
