### ISSUE TITLE
无法使用node-inspector调试

### ISSUE THREAD

**Issue by wujichao** [leancloud/avoscloud-code-command#97]
首先启动 $ node-inspector
然后打开node-inspector的浏览器前端
最后启动 $ avoscloud -d

发现 node-inspector无法检测到代码

使用 node --debug-brk test.js 测试node-inspector, node-inspector可以正确检测的test.js
尝试把runtime.js的node debug改成 node --debug-brk 可以检测到avoscloud的代码 但是检测不到main.js

**Comment by jysperm** [comment]
已在新发布的 0.9.2 版本中解决
